### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by chezstov** [atom/electron-quick-start#30] opened 2016-01-30 19:21 UTC
After
```
> git clone https://github.com/atom/electron-quick-start
> cd electron-quick-start
> npm install
> npm start
```

I get error:

```
> electron-quick-start@1.0.0 start /home/do/dev/electron-quick-start
> electron main.js

App threw an error when running [TypeError: Cannot read property 'on' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/home/do/dev/electron-quick-start/main.js:34:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/home/do/dev/electron-quick-start/node_modules/electron-prebuilt/dist/resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by vertexportus** [comment] 2016-01-31 14:09
Having the exact same problem..

Tried to use the downloaded .exe, update node, clean cache and re-install electron-prebuilt, and nothing..

I either get an error that module electron can't be found (with require('electron') ) or that app is undefined with require('electron-prebuilt')

**Comment by dmr** [comment] 2016-02-05 17:00
I have the same issue here.
Did you resolve the problem by now?

**Comment by chezstov** [comment] 2016-02-05 17:16
@dmr, no, i switched to nw.js.

**Comment by dmr** [comment] 2016-02-06 10:04
The issue is also discussed in the electron main repo:
https://github.com/atom/electron/issues/3708

```
const electron = require('electron');
const app = require('app');
const BrowserWindow = require('browser-window')
```

Solved the issue for me :)

**Comment by dmr** [comment] 2016-02-06 10:06
Anyone interested in a pull request?
Not sure how stable the new api is.

**Comment by chezstov** [comment] 2016-02-06 13:19
@dmr, I think that working example better.

**Comment by dmr** [comment] 2016-02-06 19:21
I think the issue was/is my computer. I had to manually look for a node_modules/electron folder and delete is. Sorry for the noise.

**Comment by jlord** [comment] 2016-02-07 05:22
@chezstov do you have a globally installed `electron` module?

**Comment by ibufu** [comment] 2016-02-26 02:47
@jlord 
I installed electron globally.But it still throw the same error.

**Comment by dmr** [comment] 2016-02-26 08:21
That is exactly the problem.
"electron" is not the correct package name!

Remove alle the electron installations and install electron-prebuilt, then it works.

**Comment by jlord** [comment] 2016-02-26 18:46
> That is exactly the problem.
"electron" is not the correct package name!

Yep, @dmr. :+1: 

If you have a globally installed module called `electron` (not associated with Electron.js) you'll have a conflict @ibufu. You'll need to remove it and use `electron-prebuilt` for Electron.js apps. 

// cc @chezstov @vertexportus

**Comment by jlord** [comment] 2016-03-10 00:03
Going to close this out, hopefully the last response helped others in this thread.

**Closed by jlord** 2016-03-10 00:03 UTC

**Comment by Pablodotnet** [comment] 2016-10-27 01:45
@dmr I can't make it work with that, can you put here a copy of your main.js? It would be great.

**Comment by dmr** [comment] 2016-10-27 04:28
This issue is really old. Removing node_modules and reinstalling will probably fix the issue

**Comment by TacoCoder** [comment] 2016-11-29 01:18
Removing node_modules and reinstalling didn't work for me. Any insights?

**Comment by davidcoleman007** [comment] 2016-12-07 06:05
Same for me.  electron-prebuilt is not a fix.  and .on is called on a null object.

**Comment by jawatech** [comment] 2016-12-16 03:35
The name "electron-prebuilt" is changed (back?) to "electron" since mid-2016 by the development team.
While you reinstall electron, entries in package.json should be changed accordingly.
(electron-prebuild => electron, and version number , and so on)

**Comment by benjaminsuch** [comment] 2016-12-18 20:35
The thing is, although I get this error, it's still working?! createWindow gets executed.

**Comment by boredwookie** [comment] 2016-12-28 22:01
One potential cause of this problem can be tied back to executing the electron app from a terminal extension in the Atom editor. This answer on StackOverflow helped me get past the problem: http://stackoverflow.com/a/40664925/1076507. Using a system terminal instead of platformio-ide-terminal plugin inside the Atom editor addressed my problem.

**Comment by taoteg** [comment] 2017-01-09 18:42
@boredwookie Thanks you! Made it all the way down here thinking I was borked and then found your working solution. Thank you for saving me many hours of frustrating troubleshooting. This is the issue, not sure what's up with the electron terminal extension not issuing this properly but whatever... small steps. =)

**Comment by codekraft-studio** [comment] 2017-02-05 00:42
@boredwookie man you saved me a lot of time i'm so used to that plugin that I didn't think about it

**Comment by ivorscott** [comment] 2017-03-17 16:12
@boredwookie Thank you god.

**Comment by bluemoehre** [comment] 2017-06-09 17:13
Hitting same problem on MacOS Sierra, Node 8.1.0, VSCode / Terminal / iTerm - doesn't matter. What is causing this?

**Comment by all3fox** [comment] 2017-06-13 12:33
Will second @bluemoehre here: following the [quickstart][1] to the letter, getting a `Cannot read property 'on' of undefined`. My setup is ArchLinux, `node` is managed by `nvm`:

```
nvm --version
0.33.2
node --version
v8.1.0
``` 

Also, there is a global `electron` package installed by the ArchLinux package manager and an local `electron` in `node_modules` that I install with `npm install electron --save`. Removing either global package or wiping the `node_modules` folder and reinstalling does not fix the issue.

[1]: https://electron.atom.io/docs/tutorial/quick-start/

**Comment by all3fox** [comment] 2017-06-13 12:45
Oh, apologies, my mistake. I did not know that in the line `const {app, BrowserWindow} = require('electron')` you actually cannot rename `app` and `BrowserWindow` to other varible names. That solved my issue.

**Comment by searene** [comment] 2017-06-20 13:30
I realized that I included `main.js`(which is the entry point of electron) in `index.html` again. Removing it worked.

**Comment by j-ackerman** [comment] 2017-07-29 21:01
@boredwookie thank you, this solved my issue and likely saved me hours of trial and error

**Comment by MggMuggins** [comment] 2017-08-25 20:12
@boredwookie Do you have any idea what causes this? I'd been using Terminal-Fusion (which is a Linux fork of Platformio Term), and had the same problem. Any idea what the cause is?

**Comment by gsilvestri** [comment] 2017-09-02 10:45
I'm using VS Code to develop Angular JS application and I have exactly the same problem as VS Code is built on top of Atom.

The problem is that you have the same problem using the debugger tool in VS Code... so: no Atom terminal means no debugger.

Using the Ubuntu terminal instead the Atom/VS Code terminal a workaround, not a solution: needs to find a proper solution for the problem.

**Comment by dezryth** [comment] 2017-09-13 00:31
I'm running into this as well with VS Code

**Comment by MggMuggins** [comment] 2017-09-13 00:33
Do we think it's an atom bug then, rather than the specific terminal?

**Comment by wave100** [comment] 2018-01-16 16:51
@searene Cheers, that's what I did too. Would've taken me forever to figure it out.

**Comment by avoitishin** [comment] 2018-03-21 17:21
Missing below step will cause this issue:

> Turning this Node application into an Electron application is quite simple - we merely replace the node runtime with the electron runtime.

**Comment by turok1997** [comment] 2018-03-26 14:54
For me using `"start": "electron ."` script worked. Then just call `npm start` instead of `node index.js`

**Comment by markobalogh2** [comment] 2018-05-30 20:05
One implication of this issue appears to be that an electron application cannot be launched from a node script via a `child_process` - has anyone figured out how to do this?

**Comment by MggMuggins** [comment] 2018-05-31 04:03
At this point it seems like a rather problematic electron bug. Maybe do some digging and see if you can find out what's causing it. Just happens when running via node API calls? Can you call it using the node runtime but using a lower-level interface (is there a way to use raw syscalls in node)?

**Comment by Ynoaparast** [comment] 2018-06-21 09:53
I'm very new to Electron but I figured out the solution to my problem:

I have a very basic Electron application that consists of two files:

- main.js
- index.html

I got the error  _"Uncaught TypeError: Cannot read property 'on' of undefined"_, in the dev-tools console, **despite my application opening and functioning properly.** 

My mistake:  

I had added a <script src = "path/to/main.js"> in my index.html file, because I wanted an onclick-event to call a function in my main.js   Removing this <script> tag removed the error.

**Comment by hatton** [comment] 2018-07-11 01:44
With electron 2.0, this is what works in the renderer process:

``const { app } = require("electron").remote;``

**Comment by jdevitt** [comment] 2018-09-03 18:17
The worked for me in VSCode

create .vscode folder in root and create launch.json 

{

    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\app\\YOUR ENTRY POINT.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd","runtimeArgs": [
                ".",
                "--enable-logging"
            ],
            "env": {
                
            },
            "console": "internalConsole",
            "sourceMaps": false,
        }
    ]
}

**Comment by svmi3195** [comment] 2018-10-20 16:39
For me this error happened when I, like searene above, occasionally linked `main.js` in `index.html` and removing it fixed the problem.

**Comment by emmanuel39hanks** [comment] 2018-12-25 00:53
replace your scripts with:
"scripts": {
"test": "electron .",
"start": "electron ."
}

**Comment by martinovoleg** [comment] 2019-01-27 15:46
> Я понял, что я включил `main.js`(который является точкой входа электрона) в `index.html`. Удаление это сработало.

sanks;)

**Comment by krishnappahuded** [comment] 2019-02-01 06:02
In my application it's throwing different error like
TypeError: Cannot set property '_nodeValue' of undefined TypeError: Cannot set property '_nodeValue' of undefined

If we have any solution please help me.

**Comment by EduardoSantos7** [comment] 2019-03-03 06:59
In my case the solution appears after check the [python-shell official documentation](https://www.npmjs.com/package/python-shell). 'electron' is correct and be sure to pass run function all the parameters that the function needs (following some tutorials, I was not writting arguments: `options`) also be sure to write correctly `PythonShell`

```
const { app, BrowserWindow } = require('electron')

let { PythonShell } = require('python-shell')

PythonShell.run('hello.py', null, function (err, results) {
    if (err) throw err;
    console.log('hello.py finished.');
    console.log('results', results);
});
```
Hope be useful!

**Comment by jabedhossain** [comment] 2019-04-25 20:12
> One potential cause of this problem can be tied back to executing the electron app from a terminal extension in the Atom editor. This answer on StackOverflow helped me get past the problem: http://stackoverflow.com/a/40664925/1076507. Using a system terminal instead of platformio-ide-terminal plugin inside the Atom editor addressed my problem.

Apparently this is the case why it was showing an exception in VS Code while debugging. It did run in power-shell terminal but showed exception in VS Code debugger, the solution was to add a configuration file for [debugging.](https://electronjs.org/docs/tutorial/debugging-main-process-vscode)

Make sure to uncheck, 'All Exceptions' and 'Uncaught Exceptions' from the debugger window. It should debug smoothly.

**Comment by ahmedtahabaqi** [comment] 2019-08-15 20:30
write app in lower case

**Comment by levon-isajanyan** [comment] 2019-12-09 07:41
macOS Catalina  problem solved by adding into package json _**"electron ."**_
`{
  "name": "universal-local-dev-tools",
  "version": "xxx",
  "description": "xxx ",
  "main": "xxx",
  "scripts": {
    "start": "electron .",
    "test": "electron ."
  },
  "keywords": [
    "xxx",
    "xxx"
  ],
  "author": "xxx",
  "license": "xxx",
  "dependencies": {},
  "devDependencies": {
    "electron": "xxx"
  }
}`

**Comment by jdmagic21** [comment] 2020-01-26 17:20
> 
> 
> > That is exactly the problem.
> > "electron" is not the correct package name!
> 
> Yep, @dmr. 👍
> 
> If you have a globally installed module called `electron` (not associated with Electron.js) you'll have a conflict @ibufu. You'll need to remove it and use `electron-prebuilt` for Electron.js apps.
> 
> // cc @chezstov @vertexportus

1. A package named `electrong-prebuild` can no longer be found. 
2. Installing the latest version in local node_module folder still returns this error.

**Comment by jdmagic21** [comment] 2020-01-26 17:23
> 
> 
> This issue is really old. Removing node_modules and reinstalling will probably fix the issue

Deleting you local node_modules folder and reinstalling does not fix the problem.

**Comment by jdmagic21** [comment] 2020-01-26 17:27
> 
> 
> One potential cause of this problem can be tied back to executing the electron app from a terminal extension in the Atom editor. This answer on StackOverflow helped me get past the problem: http://stackoverflow.com/a/40664925/1076507. Using a system terminal instead of platformio-ide-terminal plugin inside the Atom editor addressed my problem.

On Windows tried to use PowerShell and command prompt outside of Visual Studio. Still getting the same error.

**Comment by jdmagic21** [comment] 2020-01-26 17:37
If you use the example project you can see that they are calling `electron .` in their package.json file. If you have your code written in a different location you can rewrite this to something like the below:
```
"scripts":{
    "start": "electron ./directory/index.js"
}
````
I wish they were more transparent about this in their documentation.

**Comment by pferreirafabricio** [comment] 2020-03-09 13:41
> For me using `"start": "electron ."` script worked. Then just call `npm start` instead of `node index.js`

Thank you, this worked for me.
